pipeline {
    agent any

    environment {
        TERRAFORM_BIN = '/usr/bin/terraform'  // Đặt đúng đường dẫn Terraform
        AWS_CREDENTIALS_ID = 'AWS_CREDENTIALS' // AWS Credentials trong Jenkins
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    git branch: 'main',
                        credentialsId: 'github-token', // Sử dụng token GitHub
                        url: 'https://github.com/BenNguyen97/Jenkins_Pipeline.git'
                }
            }
        }

        stage('Init Terraform') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: AWS_CREDENTIALS_ID]
                ]) {
                    script {
                        sh '''
                            # Kiểm tra Terraform đã cài hay chưa
                            if ! command -v terraform &> /dev/null
                            then
                                echo "Terraform not found. Installing..."
                                yum install -y yum-utils
                                yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
                                yum -y install terraform
                            else
                                echo "Terraform already installed"
                            fi
                            
                            # Đảm bảo Terraform có quyền thực thi
                            chmod +x ${TERRAFORM_BIN}
                            
                            # Kiểm tra lại phiên bản Terraform
                            ${TERRAFORM_BIN} version
                        '''
                    }
                }
            }
        }

        stage('Plan Terraform') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: AWS_CREDENTIALS_ID]
                ]) {
                    script {
                        sh '${TERRAFORM_BIN} plan -out=tfplan'
                    }
                }
            }
        }

        stage('Apply Terraform') {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: AWS_CREDENTIALS_ID]
                ]) {
                    script {
                        sh '${TERRAFORM_BIN} apply -auto-approve tfplan'
                    }
                }
            }
        }
    }
}
